IzendaHours/Controllers/RecordsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using IzendaHours.Models;
using Izenda.AdHoc;

namespace IzendaHours.Controllers
{
    public class RecordsController : Controller
    {
        private IzendaHoursEntities db = new IzendaHoursEntities();

        // GET: Records
        [Authorize]
        public ActionResult Index()
        {
            if (User.Identity.IsAuthenticated)
            {
                var email = User.Identity.GetUserName();
                var name = email.Split('.');
                var firstName = name[0];
                var empId = firstName.First().ToString().ToUpper() + firstName.Substring(1);
                var records = db.Records.Include(r => r.Project).Include(r => r.Task);
                if (User.Identity.GetUserName() == "admin")
                {
                   return View(records.ToList());
                }
                return View(records.ToList().Where(user => user.EmployeeId.Contains(empId)));
            }
            return new HttpStatusCodeResult(HttpStatusCode.Forbidden);
        }

        // GET: Records/Details/5
        [Authorize]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Record record = db.Records.Find(id);
            if (record == null)
            {
                return HttpNotFound();
            }
            return View(record);
        }

        // GET: Records/Create
        [Authorize]
        public ActionResult Create()
        {
            if (User.Identity.IsAuthenticated)
            {
                ViewBag.ProjectId = new SelectList(db.Projects.OrderBy(model => model.Project1), "ProjectId", "Project1");
                ViewBag.TaskId = new SelectList(db.Tasks, "TaskId", "Task1");
                return View();
            }
            return new HttpStatusCodeResult(HttpStatusCode.Forbidden);
        }

        // POST: Records/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "EntryId,EmployeeId,TaskId,CaseNo,ProjectId,Hours,WikiLink,Notes,RecordDate")] Record record, string Command)
        {
            if (ModelState.IsValid)
            {
                var email = User.Identity.GetUserName();
                var name = email.Split('.');
                var firstName = name[0];
                record.EmployeeId = firstName.First().ToString().ToUpper() + firstName.Substring(1);
                db.Records.Add(record);
                db.SaveChanges();
                if (Command == "Create & New")
                {
                    return RedirectToAction("Create");
                }
                return RedirectToAction("Index");
            }


            ViewBag.ProjectId = new SelectList(db.Projects, "ProjectId", "Project1", record.ProjectId);
            ViewBag.TaskId = new SelectList(db.Tasks, "TaskId", "Task1", record.TaskId);
            return View(record);
        }

        // GET: Records/Create Partial View (Table)
        [ChildActionOnly]
        public ActionResult _CreateRecordsTable()
        {
            var email = User.Identity.GetUserName();
            var name = email.Split('.');
            var firstName = name[0];
            var records = db.Records.Include(r => r.Project).Include(r => r.Task);
            var todaysRecords = records.ToList()
                .Where(user => user.EmployeeId.Contains(firstName.First().ToString().ToUpper() + firstName.Substring(1)))
                .Where(d => d.RecordDate == DateTime.Today);
            return PartialView(todaysRecords);
        }

        // GET: Records/Edit/5
        [Authorize]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Record record = db.Records.Find(id);
            if (record == null)
            {
                return HttpNotFound();
            }

            ViewBag.ProjectId = new SelectList(db.Projects.OrderBy(model => model.Project1), "ProjectId", "Project1", record.ProjectId);
            ViewBag.TaskId = new SelectList(db.Tasks, "TaskId", "Task1", record.TaskId);
            return View(record);
        }

        // POST: Records/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "EntryId,EmployeeId,TaskId,CaseNo,ProjectId,Hours,WikiLink,Notes,RecordDate")] Record record)
        {
            var email = User.Identity.GetUserName();
            var name = email.Split('.');
            var firstName = name[0];

            if (ModelState.IsValid)
            {
                record.EmployeeId = firstName.First().ToString().ToUpper() + firstName.Substring(1);
                db.Entry(record).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            
            ViewBag.ProjectId = new SelectList(db.Projects, "ProjectId", "Project1", record.ProjectId);
            ViewBag.TaskId = new SelectList(db.Tasks, "TaskId", "Task1", record.TaskId);
            return View(record);
        }

        // GET: Records/Delete/5
        [Authorize]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Record record = db.Records.Find(id);
            if (record == null)
            {
                return HttpNotFound();
            }
            return View(record);
        }

        // GET: Records/Reporting
        [Authorize]
        public ActionResult Reporting()
        {
            if (User.Identity.IsAuthenticated)
            {
                //HttpCookie myCookie = new HttpCookie("AdHocLogin");
                //myCookie["UserName"] = User.Identity.GetUserName();
                //myCookie.Expires = DateTime.Now.AddDays(1d);
                //Response.Cookies.Add(myCookie);
                return View();
            }
            return new HttpStatusCodeResult(HttpStatusCode.Forbidden);
        }

        // POST: Records/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Record record = db.Records.Find(id);
            db.Records.Remove(record);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        [Authorize]
        public ActionResult Welcome()
        {
            return View();
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

IzendaHours/Views/Shared/_Layout.cshtml
@using Microsoft.AspNet.Identity
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Izenda Engineering</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <link rel="stylesheet" type="text/css" href="~/Content/Custom.css">
    <link href="http://ajax.googleapis.com/ajax/libs/jqueryui/1.7.0/themes/base/jquery-ui.css" rel="stylesheet" type="text/css" />
    
    <link rel="shortcut icon" href="~/favicon.ico">

    <meta name="description" content="A timesheet application for the Izenda Engineering team" />
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @*<div class="container-fluid">
                        <div class="navbar-header">
                            <a class="navbar-brand" href="#">
                                <img alt="Brand" class="img-responsive" src="~/Resources/IzendaNewLogoBlue.png">
                            </a>
                        </div>
                    </div>*@
                @if (User.Identity.IsAuthenticated)
                {
                    @Html.ActionLink("Izenda Hours Sheet", "Welcome", "Records", new { area = "" }, new { @class = "navbar-brand" })
                }
                else { 
                @Html.ActionLink("Izenda Hours Sheet", "Index", "Records", new { area = "" }, new { @class = "navbar-brand" })
                }
            </div>
            <div class="navbar-collapse collapse">
                @if (User.Identity.IsAuthenticated)
                {
                    <ul class="nav navbar-nav">
                        <li>@Html.ActionLink("Timesheet", "Index", "Records")</li>
                        <li>@Html.ActionLink("Record", "Create", "Records")</li>
                        <li>@Html.ActionLink("Reporting", "ReportList", "Reporting")</li>
                    </ul>
                }
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
    </div>
    <footer>
        <p>&copy; @DateTime.Now.Year - Izenda, Inc.</p>
    </footer>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
    <script src="//code.jquery.com/ui/1.11.4/jquery-ui.js"></script>
    <!-- DataTables CSS -->
    @*<link rel="stylesheet" type="text/css" href="//cdn.datatables.net/1.10.5/css/jquery.dataTables.css">*@
    <link rel="stylesheet" type="text/css" href="//cdn.datatables.net/plug-ins/1.10.6/integration/bootstrap/3/dataTables.bootstrap.css">

    <!-- DataTables -->
    <script type="text/javascript" charset="utf8" src="//cdn.datatables.net/1.10.5/js/jquery.dataTables.js"></script>
    <script type="text/javascript" charset="utf8" src="//cdn.datatables.net/plug-ins/1.10.6/integration/bootstrap/3/dataTables.bootstrap.js"></script>
    <script type="text/javascript" charset="utf-8" src="//cdn.datatables.net/plug-ins/1.10.6/api/sum().js"></script>
    <script type="text/javascript" src="~/Scripts/jquery.dataTables.columnFilter.js"></script>

    <!--Select2 Scripts-->
    <link href="//cdnjs.cloudflare.com/ajax/libs/select2/4.0.0/css/select2.min.css" rel="stylesheet" />
    <script src="//cdnjs.cloudflare.com/ajax/libs/select2/4.0.0/js/select2.min.js"></script>

    <!--Custom Scripts-->
    <script src="~/Content/hours.js"></script>

</body>
</html>

IzendaHours/Views/Shared/_ReactLayout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
</head>
<body>
<div id="app"></div>

<script src="https://fb.me/react-0.14.7.js"></script>
<script src="https://fb.me/react-dom-0.14.7.js"></script>
<script src="@Url.Content("~/build/main.bundle.js")"></script>
<div>
    @RenderBody()
</div>
</body>
</html>

IzendaHours/Views/Shared/_SiteLayout.cshtml
@*@model System.Web.Mvc.ViewMasterPage*@
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">

<html>
<head>
    <title>Izenda Reports</title>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta http-equiv="Expires" content="0" />
    <meta http-equiv="Pragma" content="no-cache" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta name="robots" content="noindex, follow" />
    <link rel="alternate" href="" title="Team Blog - RSS" type="application/rss+xml" />
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    
    
    <link rel="stylesheet" href="~/Reporting/Resources/css/ModernStyles/reset2.css" type="text/css" />
    <link rel="stylesheet" href="~/Reporting/Resources/css/ModernStyles/print.css" type="text/css" media="print" />
    <link rel="stylesheet" href="~/Reporting/Resources/css/ModernStyles/fun.css" type="text/css" />
    
    
    <link rel="shortcut icon" href="~/Reporting/Resources/FromDLL/Resources/ModernImages/report-icon.png" type='image/png' />
    
    @if (IsSectionDefined("changeableheader"))
    {
        @RenderSection("changeableheader");
    }
    else
    {
        <link rel="stylesheet" type="text/css" href="./rs.aspx?css=ModernStyles.bootstrap-responsive" />
        <link rel="stylesheet" type="text/css" href="./rs.aspx?css=ModernStyles.bootstrap" />
        <link rel="stylesheet" type="text/css" href="./rs.aspx?css=ModernStyles.bootstrap-modals" />
        <link rel="stylesheet" type="text/css" href="./rs.aspx?css=ModernStyles.bootstrap-override" />
        <script type="text/javascript" src="./rs.aspx?js=ModernScripts.jquery-1.7.2.min"></script>
    }
    <script type="text/javascript" src="~/Reporting/Resources/js/main.js"></script>
    @*<script type="text/javascript" src="./rs.aspx?js=ModernScripts.bootstrap-dropdown"></script>*@
    <script type="text/javascript" src="./rs.aspx?js=ModernScripts.bootstrap-tab"></script>
    <script type="text/javascript" src="./rs.aspx?js=ModernScripts.bootstrap-transition"></script>
    <script type="text/javascript" src="./rs.aspx?js=ModernScripts.bootstrap-modal"></script>
    
    <link rel="stylesheet" type="text/css" href="~/Content/Custom.css" id="customstyle" />
    <link rel="stylesheet" href="~/Reporting/Resources/css/newmain.css" type="text/css" />

    @if (IsSectionDefined("header"))
    {
        @RenderSection("header")
    }
    @if (!Izenda.AdHoc.AdHocSettings.ShowDesignLinks)
    {
      string script = "<script type=\"text/javascript\" language=\"javascript\">";
          script += "try { $(document).ready(function() {$('.designer-only').hide(); });}catch(e){}";
          script += " try{ jq$(document).ready(function() {jq$('.designer-only').hide(); });}catch(e){} ";
          script += "</script>";
        @Html.Raw(script);
    }
</head>

<body style="margin:0; padding-top:65px;">

    @*<div class="layout">
        <div class="header applyStyles" id="whiteHeader">
            <div class="page" style="font-family: Segoe UI,Tahoma,Verdana,Arial,Helvetica,sans-serif">
                <div class="left-logo">
                    <img src="~/Resources/FromDLL/Resources/ModernImages/bi-logo.png" alt="Business intelligence" />
                </div>
                <div class="right-logo">
                    <a href="http://izenda.com" style="position: relative; top: 4px;"><img runat="server" class="right-logo" ID="rightLogo" src="~/Resources/FromDLL/Resources/ModernImages/IzendaNewLogoBlue.png" alt="Izenda Reports" /></a>
                </div>
                <div class="clearfix"></div>
            </div>
        </div>*@

        <script type="text/javascript">
            function insertParam(key, value) {
                key = escape(key); value = escape(value);
                var kvp = document.location.search.substr(1).split('&');
                if (kvp.length == 1 && kvp[0] == '')
                    kvp.length = 0;
                var i = kvp.length; var x; while (i--) {
                    x = kvp[i].split('=');
                    if (x[0] == key) {
                        x[1] = value;
                        kvp[i] = x.join('=');
                        break;
                    }
                }
                if (i < 0) { kvp[kvp.length] = [key, value].join('='); }
                document.location.search = kvp.join('&');
            }

            function ShowRlToDbLoading() {
                document.getElementById('mainContentDiv').style.display = 'none';
                var dld = document.getElementById('dashLoadingVg');
                dld.style.height = document.body.scrollHeight + 'px';
                dld.style.display = '';
                var limg = document.getElementById('limgDb');
                var lw = document.getElementById('loadingWordDb');
                var vSize = document.body.offsetHeight;
                lw.style.paddingTop = (3 + vSize / 3) + 'px';
            }
        </script>

    <div id="reportingNav" class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @*<div class="container-fluid">
                        <div class="navbar-header">
                            <a class="navbar-brand" href="#">
                                <img alt="Brand" class="img-responsive" src="~/Resources/IzendaNewLogoBlue.png">
                            </a>
                        </div>
                    </div>*@

               
            </div>
            <div class="navbar-collapse collapse">
               
                    <ul class="nav navbar-nav">
                        <li>@Html.ActionLink("Reports", "ReportList", "Reporting")</li>
                        <li>@Html.ActionLink("Dashboards", "Dashboards", "Reporting")</li>
                        <li class="dropdown">
                            <a class="dropdown-toggle" data-toggle="dropdown" href='@Url.Action("ReportDesigner", "Reporting", new { clear = 1, tab = "Data+Sources" })'>New<b class="caret"></b></a>
                            <ul class="dropdown-menu" role="menu">
                                <li>@Html.ActionLink("Report", "ReportDesigner", "Reporting", new { clear = 1, tab = "Data+Sources" }, null)</li>
                                <li>@Html.ActionLink("Instant Report", "InstantReportNew", "Reporting")</li>
                                <li>@Html.ActionLink("Dashboard", "Dash", "Reporting")</li>
                            </ul>
                        </li>
                    </ul>
                <ul class="nav navbar-nav navbar-right">
                    <li> @Html.ActionLink("Izenda Hours Sheet", "Welcome", "Records", new { area = "" }, new { @class = "navbar-brand" })</li>
                    </ul>
</div>
        </div>
    </div>

    <div class="izenda-bs">
        <div id="dashLoadingVg" style="text-align: center; width:100%; height:100%; top:130px; left:0; background-color: #FFFFFF; z-index: 8000; display: none;">
            <div id="loadingWordDb" style="font-size: 20px;margin-left: 70px;color:#1D5987;font-family:Verdana,Arial,Helvetica,sans-serif;font-weight:normal !important;font-style: normal;">Loading...</div>
            <img id="limgDb" style="margin-left: 70px; margin-top:40px;" src="@Url.Content("~/Reporting/rs.aspx?image=loading.gif")" alt="" />
        </div>

        <div class="main-content" id="mainContentDiv">
            @RenderBody()
        </div>

        <div class="footer applyStyles">
            <div class="line"></div>
            <div class="page">
                <p>
                    Copyright 2015 Izenda, Inc<br />
                    <a href="http://izenda.com">Home</a> <em style="margin: 0 .25em;">·</em>@Html.ActionLink("Reports", "ReportList", @HttpContext.Current.Request.RequestContext.RouteData.Values["controller"].ToString()) <em style="margin: 0 .25em;">·</em> <a href="http://blog.izenda.com">Blog</a>
                </p>
            </div>
        </div>

    </div>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>